# Generated by Django 2.2 on 2019-05-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190530_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartype',
            old_name='category_summary',
            new_name='car_summary',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='series_summary',
            new_name='manufacturer_summary',
        ),
    ]
