# Generated by Django 2.2 on 2019-05-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190530_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartype',
            old_name='category_slug',
            new_name='car_slug',
        ),
    ]
