# Generated by Django 2.2 on 2019-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190531_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='tutorial_slug',
            new_name='model_slug',
        ),
    ]
