# Generated by Django 2.2 on 2019-06-03 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190531_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='last edited'),
        ),
    ]
