# Generated by Django 2.2 on 2019-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190604_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_summary',
            field=models.CharField(max_length=2000),
        ),
    ]
