# Generated by Django 2.2 on 2019-06-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190607_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_summary',
            field=models.TextField(),
        ),
    ]
